#!/usr/bin/env bash
# haproxy

apt-get -y update
apt-get -y install haproxy=1.6.\*
echo "backend web-backend
        balance roundrobin
        server 1895-web-01 35.196.36.101:80 check
        server 1895-web-02 35.231.20.160:80 check" >> /etc/haproxy/haproxy.cfg
echo "frontend http
        bind *:80\
        mode http
        default_backend web-backend" >> /etc/haproxy/haproxy.cfg
service haproxy restart
