#!/usr/bin/env bash
# script to fix Nginx on port 80

sed -i -e "s/listen 8080 default_server;/listen 80 default_server;/g" /etc/nginx/sites-enabled/default
sed -i -e "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server ipv6only=on;/g" /etc/nginx/sites-enabled/default
service nginx restart
