#!/usr/bin/env bash
# this script Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid
# and terminates itself when receiving a SIGQUIT or SIGTERM signal

sig_term() {
	rm -f /var/run/holbertonscript.pid
	echo "I hate the kill command"
	exit 0
}

sig_quit() {
	rm -f /var/run/holbertonscript.pid
	exit 0
}

sig_int() {
	echo "Y U no love me?!"
	exit 0
}


trap sig_term TERM
trap sig_quit QUIT
trap sig_int INT

$$ > /var/run/holbertonscript.pid

while (true); do
	echo "To infinity and beyond"
    sleep 1
done

