#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
i=0
while [ $i -lt 11 ]
do
    if [[ $i -eq 9 ]]
    then
        echo "hi"
    else
        echo "Holberton School"
    fi
    i=$(( i + 1 ))
done