#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
h=0
while [ $h -lt 13 ]
do
    echo "Hour: $h"
    while [ $m -lt 60 ]
    do
        echo $m
        m=$(( m + 1 ))
    done
    m=0
    h=$(( h + 1))
done